# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           none
relative_permalinks: true

# Setup
title:               Aaron H. Kim
tagline:             Fearless voyager
url:                 http://blog.ahkim.com
paginate:            10
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

safe: true
highlighter: pygments
lsi: false

markdown:     redcarpet

redcarpet:
    extensions: 
      - no_intra_emphasis
      - fenced_code_blocks
      - tables
      - strikethrough
      - superscript
      - autolink
      - hard_wrap

# redcarpet:
#    extensions: ["smart"]

gems:
  - jemoji

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Aaron Kim
  url:               http://blog.ahkim.com
  email:             info@ahkim.com
  github:	     w12ard
  twitter: 	     w12ard 
# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/w12ard/w12ard.github.io/