# Dependencies
highlighter:      rouge

# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           none

# Setup
title:               Aaron H. Kim
tagline:             Fearless voyager
url:                 http://blog.ahkim.com
paginate:            1
encoding: 	     UTF-8
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Aaron Kim
  url:               http://blog.ahkim.com
  email:             info@ahkim.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/w12ard/w12ard.github.io/
